### ISSUE TITLE
Really really hate to bother but

### ISSUE THREAD

**Issue by Icesythe7** [r-lyeh/tinybits#1]
I noticed you posted some code here [https://github.com/ocornut/imgui/issues/1658](url) and was searching in your code trying to find if you had improved upon it or any of your other cool snippets for imgui and can't seem to find any anywhere, I had no other way to contact you so I apologize for creating an issue here. If there is a better method to communicate with you about some of your imgui stuff please inform me, and thanks for your time!

**Comment by r-lyeh** [comment]
Hello @Icesythe7 

No probs :D I think I have a somewhat improved version somewhere else but havent been tested that much. I can recover it next monday if you want to. There are some more imgui collected snippets here at the moment: https://github.com/r-lyeh/AVA/tree/master/editor/imgui/gists (those prefixed with `imgui_` are my own). Pic of all together here:

![image](https://user-images.githubusercontent.com/35402248/60768922-ed342900-a0c9-11e9-8b6d-f66ca447ceeb.png)
